Add Trivy failure gate

diff --git a/.github/workflows/trivy-scan.yml b/.github/workflows/trivy-scan.yml
--- a/.github/workflows/trivy-scan.yml
+++ b/.github/workflows/trivy-scan.yml
@@ -46,19 +46,16 @@ jobs:
 
           echo "TODO: Cache Trivy Database"
 
-      - name: Trivy File System Scan
+      # This job will never fail. It is designed to ALWAYS upload results.
+      - name: Trivy File System Reporting Scan
         run: |
-          echo "Commencing Trivy Scan..."
-          trivy fs --scanners vuln,license,secret,misconfig ${{ github.workspace }} --format sarif -o trivy-fs-scan.sarif
+          echo "Commencing Trivy Reporting Scan..."
+          trivy fs --exit-code 0 --license-full --scanners vuln,license,secret,misconfig ${{ github.workspace }} --format sarif -o trivy-fs-scan.sarif
           
-          echo "TODO: Fail on Criticals"
-
           echo "Constructing payload for upload to GitHub."
           echo '{"commit_sha":"${{ github.sha }}","ref":"${{ github.ref }}","sarif":"'$(gzip -c trivy-fs-scan.sarif | base64 -w0)'"}' > sarif_payload.json
 
           echo "Uploading SARIF payload to GitHub."
-
-          echo "TODO: Always upload, even if previous scan job fails."
 
           wget --method=POST \
             --header "Accept: application/vnd.github.v3+json" \
@@ -67,3 +64,12 @@ jobs:
             --body-file=sarif_payload.json \
             --content-on-error \
             "https://api.github.com/repos/${{ github.repository }}/code-scanning/sarifs"
+
+      # Rather than re-run our Trivy scan, we can simply use GREP to count for any issues.
+      - name: Trivy Failure Gate
+        run: |
+          echo "Checking for CRITICAL issues..."
+          grep -qE '"Severity": "CRITICAL"' $TRIVY_RESULTS_FILE && { echo "CRITICAL severity issues found in Trivy scan results."; exit 1; }
+        
+          echo "Checking for HIGH or CRITICAL issues..."
+          grep -qE '"Severity": "HIGH"|"Severity": "CRITICAL"' $TRIVY_RESULTS_FILE && { echo "High or critical severity issues found in Trivy scan results."; exit 1; }
